// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UKBatch.Storage.EntityFrameworkCore;

#nullable disable

namespace UKBatch.Storage.EntityFrameworkCore.Migrations.Sqlite
{
    [DbContext(typeof(SqliteUKBatchDbContext))]
    partial class SqliteUKBatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("UKBatch.Storage.EntityFrameworkCore.Entities.ApprovalGateEntity", b =>
                {
                    b.Property<string>("ApprovalId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchDefinitionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchStepId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeadlineUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecidedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingSinceUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("ApprovalId");

                    b.HasIndex("Status");

                    b.ToTable("ApprovalGates", (string)null);
                });

            modelBuilder.Entity("UKBatch.Storage.EntityFrameworkCore.Entities.BatchDefinitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailurePolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("OnFailureSteps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Schedule")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Source", "CreatedAtUtc");

                    b.HasIndex("Source", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_BatchDefinitions_Source_Name");

                    b.ToTable("BatchDefinitions", (string)null);
                });

            modelBuilder.Entity("UKBatch.Storage.EntityFrameworkCore.Entities.BatchRunEntity", b =>
                {
                    b.Property<string>("BatchId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Cancelled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentStepIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Failed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("StepCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("BatchId");

                    b.HasIndex("BatchDefinitionId", "StartedAtUtc");

                    b.HasIndex("Status", "StartedAtUtc");

                    b.ToTable("BatchRuns", (string)null);
                });

            modelBuilder.Entity("UKBatch.Storage.EntityFrameworkCore.Entities.JobExecutionEntity", b =>
                {
                    b.Property<string>("ExecutionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchDefinitionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchStepId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnqueuedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Failed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Processed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Total")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("ExecutionId");

                    b.HasIndex("BatchId");

                    b.HasIndex("BatchDefinitionId", "EnqueuedAtUtc");

                    b.HasIndex("JobName", "EnqueuedAtUtc");

                    b.HasIndex("Status", "EnqueuedAtUtc");

                    b.ToTable("JobExecutions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
